IDEM-245
dltxio/proxy.idem.com.au pull request #23
Opened 2022-07-22 06:46 UTC by pondpiu

#245

endpoint for requestOtp from verify phone number flow

2022-07-25 09:58 UTC, bitcoinbrisbane commented on src/user/user.service.ts
> +        await this.smsService.send(mobileNumber, smsMessage);
I think we can just call it a message and can we use a template?

```suggestion
        const message = `Your OTP code for IDEM is ${otp}`;
        await this.smsService.send(mobileNumber, message);
```

2022-07-25 09:58 UTC, bitcoinbrisbane requested changes
One thing to look at

2022-07-26 01:48 UTC, xiangzhe0812 approved these changes

2022-07-26 02:00 UTC, JasminFarhi approved these changes

2022-07-26 02:00 UTC, bitcoinbrisbane approved these changes

2022-07-26 02:01 UTC, merged