IDEM-9
dltxio/proxy.idem.com.au pull request #49
Opened 2022-08-24 23:40 UTC by pondpiu

#9

2022-08-25 02:10 UTC, xiangzhe0812 commented on .env.local
> +PROXY_API_URL= "http://localhost:3000/user"
Need api url in .env.developement and env.production as well.

2022-08-25 02:10 UTC, xiangzhe0812 commented on src/auth/auth-anonymous.guard.ts
> +import { AuthGuard } from "@nestjs/passport";
Can we change the file name to auth-local-guard  somthing.

2022-08-25 02:10 UTC, xiangzhe0812 commented on src/user/user.controller.ts
> +        const isSuccess = await this.userService.verifyEmail(email, token);
Do we need this return?

2022-08-25 03:22 UTC, bitcoinbrisbane requested changes
1. Font doesnt look the same as the site
2. What is hpbs?
3. The webpage should be on our site, not the proxy
4. The ooops doesnt look good.

2022-08-25 04:48 UTC, xcjlo985 commented
As discussed with @pondpiu and @xiangzhe0812 the implementation will change. Probably new PRs

2022-08-25 06:02 UTC, xcjlo985 approved these changes

2022-08-25 06:02 UTC, xcjlo985 commented on src/interfaces.ts
> +    JWT_EXPIRATION_TIME = "JWT_EXPIRATION_TIME"
Replace TIME with the unit

2022-08-25 06:20 UTC, xiangzhe0812 approved these changes

2022-08-25 06:20 UTC, xcjlo985 approved these changes

2022-08-25 12:14 UTC, bitcoinbrisbane commented on src/user/user.service.ts
> +            });
Should we trim and to lower the email?

2022-08-25 12:17 UTC, bitcoinbrisbane commented on .env.development
> +JWT_EXPIRATION_SECONDS="21600"
do we need quotes here?
```suggestion
JWT_EXPIRATION_SECONDS=21600
```

2022-08-25 12:17 UTC, bitcoinbrisbane commented on .env.local
> +JWT_EXPIRATION_SECONDS="21600"
And here

```suggestion
JWT_EXPIRATION_SECONDS=21600
```

2022-08-26 03:41 UTC, xcjlo985 approved these changes

2022-08-26 04:29 UTC, xiangzhe0812 approved these changes

2022-08-26 04:43 UTC, bitcoinbrisbane approved these changes

2022-08-26 04:43 UTC, merged